GET http://localhost:10001/movies/
Accept: application/json

###

GET http://localhost:10001/movies/5
Accept: application/json

###

DELETE http://localhost:10001/movies/1
Content-Type: application/json

###

PUT http://localhost:10001/movies/5
Content-Type: application/json

{
  "id": 5,
  "user": "aaaaa",
  "rating": 511,
  "book_id": 111
}

###

POST http://localhost:10001/movies/
Content-Type: application/json

{
  "user": "MUDAK",
  "rating": 15,
  "book_id": 133
}
